import { useEffect, useRef, useState } from "react";
import { socket } from "../lib/api/socket";
import {
  CANVAS_CLICK,
  CANVAS_KEYDOWN,
  ICE_CANDIDATE,
  JOIN_ROOM,
  PAGE_FRAME,
  SDP_ANSWER,
  SDP_OFFER,
  USER_JOINED,
  USER_LEFT,
} from "../types/socket.message";
import type {
  ICE_CANDIDATE_EMIT,
  PAGE_FRAME_EMIT,
  SDP_ANSWER_EMIT,
  SDP_OFFER_EMIT,
  USER_JOINED_EMIT,
} from "../types/socket.emit";

const Video = () => {
  const mediaConstraints = {
    video: {
      width: { max: 720 },
      height: { max: 720 },
    },
  };
  const localVideoRef = useRef<HTMLVideoElement>(null);
  const remoteVideoRef = useRef<HTMLVideoElement>(null);

  const canvasRef = useRef<HTMLCanvasElement>(null);

  const localStreamRef = useRef<MediaStream | null>(null);
  const peerConnectionRef = useRef<RTCPeerConnection | null>(null);

  // Public STUN servers to fetch our public IP and Port (helps bypass NAT)
  const peerConfiguration: RTCConfiguration = {
    iceServers: [
      {
        urls: [
          "stun:stun1.l.google.com:19302",
          "stun:stun2.l.google.com:19302",
        ],
      },
    ],
  };

  const createPeerConnection = (media: MediaStream) => {
    const peerConnection = new RTCPeerConnection(peerConfiguration);
    peerConnectionRef.current = peerConnection;

    // 1. Add local media tracks to the PeerConnection so they can be sent to the peer
    media.getTracks().forEach((track) => {
      peerConnection.addTrack(track, media);
    });

    // 2. Listen for remote audio/video tracks sent by the other peer
    peerConnection.ontrack = (event) => {
      if (remoteVideoRef.current) {
        remoteVideoRef.current.srcObject = event.streams[0];
      }
    };

    // 3. Listen for local ICE candidates generated by the browser, and send them to the peer via signaling
    peerConnection.onicecandidate = (event) => {
      if (event.candidate) {
        socket.emit(ICE_CANDIDATE, { roomId, iceCandidate: event.candidate });
      }
    };
    return peerConnection;
  };

  const [inRoom, setInRoom] = useState(false);
  const roomId = "room-100";
  useEffect(() => {
    navigator.mediaDevices
      .getUserMedia(mediaConstraints)
      .then((stream) => {
        localStreamRef.current = stream;
        if (localVideoRef.current) {
          localVideoRef.current.srcObject = stream;
        }
      })
      .catch((error) => {
        console.error("Error accessing media devices.", error);
      });

    socket.on("connect", () => {
      console.log(
        `connected to the signaling socket room socket ID:${socket.id}`,
      );
      socket.emit(JOIN_ROOM, { roomId });
      setInRoom(true);
    });

    // Step A: You are already in the room. A new user joins. You are the CALLER or the first person who needs to create offer.
    socket.on(USER_JOINED, async (data: USER_JOINED_EMIT) => {
      alert(`client ${data.userId} joined the room`);
      if (!localStreamRef.current) {
        console.warn("Local stream not ready yet.");
        return;
      }
      const pc = createPeerConnection(localStreamRef.current);

      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);
      // Send the offer to the new user via our server
      socket.emit(SDP_OFFER, { roomId, sdp: offer });
    });

    // Step B: You just joined. You receive an SDP Offer. You are the CALLEE or who recieves the offer.
    socket.on(SDP_OFFER, async (data: SDP_OFFER_EMIT) => {
      if (!localStreamRef.current) {
        console.warn("Local stream not ready yet.");
        return;
      }
      const pc = createPeerConnection(localStreamRef.current);

      // Set their offer as remote configuration
      await pc.setRemoteDescription(new RTCSessionDescription(data.sdp));
      // Create answer
      const answer = await pc.createAnswer();
      // Set our answer as local description
      await pc.setLocalDescription(answer);

      // Send the answer to the other peer via signaling
      socket.emit(SDP_ANSWER, {
        roomId,
        sdp: answer,
      });
    });

    // Step C: You sent an offer. You receive their SDP Answer.
    socket.on(SDP_ANSWER, async (data: SDP_ANSWER_EMIT) => {
      const pc = peerConnectionRef.current;
      if (pc) {
        pc.setRemoteDescription(new RTCSessionDescription(data.sdp));
      }
    });

    socket.on(ICE_CANDIDATE, async (data: ICE_CANDIDATE_EMIT) => {
      const pc = peerConnectionRef.current;
      if (pc && data.iceCandidate) {
        await pc.addIceCandidate(data.iceCandidate);
      }
    });

    // Step E: A user leaves the room. Clean up the connection and UI.
    socket.on("user-left", (data: { userId: string }) => {
      console.log(`User left the room: ${data.userId}`);

      // 1. Close the WebRTC connection instance
      if (peerConnectionRef.current) {
        peerConnectionRef.current.close();
        peerConnectionRef.current = null; // Reset the ref to null
      }
      // 2. Clear the remote video stream in the UI
      if (remoteVideoRef.current) {
        remoteVideoRef.current.srcObject = null;
      }
    });

    // WebRTC connection is handled dynamically via sdp-offer and ontrack events.

    return () => {
      socket.off("connect");
      socket.off(USER_JOINED);
      socket.off(SDP_OFFER);
      socket.off(SDP_ANSWER);
      socket.off(ICE_CANDIDATE);
      socket.off(USER_LEFT);
      socket.off(PAGE_FRAME);
      socket.disconnect();
    };
  }, []);

  const handleStartConnection = () => {
    // Trigger socket connection
    socket.connect();
  };
  const handleCanvasClick = (event: React.MouseEvent<HTMLVideoElement>) => {
    const video = remoteVideoRef.current;
    if (!video) return;
    const rect = video.getBoundingClientRect();

    // Calculate click coordinates relative to the video element bounds
    const relativeX = event.clientX - rect.left;
    const relativeY = event.clientY - rect.top;

    // Scale coordinates to match the virtual browser's 800x600 viewport
    const targetX = (relativeX / rect.width) * 800;
    const targetY = (relativeY / rect.height) * 600;

    console.log(`[Frontend] Click. Scaled coordinates: x=${targetX}, y=${targetY}`);

    // Emit coordinates to the backend
    socket.emit(CANVAS_CLICK, { roomId, x: targetX, y: targetY });
  };

  const handleCanvasKeyDown = (event: React.KeyboardEvent<HTMLVideoElement>) => {
    event.preventDefault();
    const key = event.key;
    console.log(`[Frontend] Key pressed: ${key}`);
    socket.emit(CANVAS_KEYDOWN, { roomId, key });
  };

  return (
    <div>
      <h1>real time video call with webrtc simulated</h1>
      <p>{inRoom ? "online" : "offline"}</p>
      <div className="flex flex-row gap-3">
        <video id="localVideo" ref={localVideoRef} playsInline autoPlay muted width="200"></video>
        
        {/* The Interactive Virtual Browser Video Player */}
        <div>
          <h3>Virtual Browser Stream (WebRTC)</h3>
          <video
            id="remoteVideo"
            ref={remoteVideoRef}
            onClick={(e) => handleCanvasClick(e)}
            onKeyDown={(e) => handleCanvasKeyDown(e)}
            tabIndex={0} // Makes the video element focusable for typing
            playsInline
            autoPlay
            style={{ 
              border: "2px solid #334155", 
              background: "#0f172a", 
              width: "800px", 
              height: "600px", 
              outline: "none", 
              cursor: "text" 
            }}
          ></video>
        </div>
      </div>

      <div className="flex justify-center">
        <button onClick={handleStartConnection}>Connect socket</button>
        <button
          id="startBtn"
          className="bg-green-500 text-white p-4 rounded-lg"
        >
          Start
        </button>
        <button id="callBtn" className="bg-blue-500 text-white p-4 rounded-lg">
          Call
        </button>
        <button id="endBtn" className="bg-red-500 text-white p-4 rounded-lg">
          End
        </button>
      </div>
    </div>
  );
};

export default Video;
